apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backend-health-check
  namespace: yolo-app
spec:
  healthCheck:
    checkIntervalSec: 20
    timeoutSec: 10
    port: 5001
    type: HTTP
    requestPath: /api/products